name: render-cold-start
on:
  schedule:
    - cron: '1/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: |
          curl https://librechat-5nky.onrender.com/
